<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="An online shop to buy your agricultural products including food stuff, farm tools,
    raw foods, farm machineries">
    <meta name="keywords" content="Agricultural products, Agro, E-Commerce, shop, online store, 
    food stuff, Marketlada, buy, raw foods, farm tools, farm machineries">
    <title>Terms and Conditions</title>
    <link rel="stylesheet" href="/css/styles.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans&family=Ribeye&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
</head>
<body class="general-style" id="top-of-site">
    <div class="container footer_pages terms-body">
        <div class="child-container">
            <header class="mobile-header desktop-top-header">
                <div class="first-part-header">
                @include('partials.frontend._cartii')
                    <div class="mobile-logo-search-container">
                        @include('partials.frontend._searchiii')
                    </div>
                    @include('partials.frontend._navbarii')
                </div>   
            </header>
            <main>
                <section>
                    <div class="page-title-container">
                        <hr>
                        <h1>Terms and conditions</h1>
                        <hr>
                    </div>
                    <div class="content">
                       <section>
                            <h2>Customer Service</h2>
                            <div>
                                <p class="top-text">
                                    This document is an electronic record in terms with the National Information 
                                    Technology Development Agency Act, 2007 and rules there under as applicable 
                                    and the amended provisions pertaining to electronic records in various statutes 
                                    as amended by the National Information Technology Development Agency Act, 2007. 
                                    This electronic record is generated by a computer system and does not require any 
                                    physical or digital signatures. 
                                </p>
                                <p class="each-p">
                                    Your use of the Marketlada.com website www.Marketlada.com (hereinafter referred to as 
                                    “Marketlada.com.com.") and tools are governed by the following terms and conditions as 
                                    applicable to Marketlada.com.com. If you transact on Marketlada.com.com, you shall be 
                                    subject to the policies that are applicable to the website for such transaction. By mere 
                                    use of the website you shall be contracting with Marletlada Limited, a company incorporated 
                                    under Companies and Allied Matters Act, 2004 with Head office at House 5 (Plot 128) 3rd Avenue
                                    D Close Federal Housing Estate (Agip) Mile 4rumueme Port Harcourt Rivers State, Nigeria and these 
                                    terms and conditions constitute your binding obligations. 
                                </p>
                                <p class="each-p">
                                    For the purpose of these terms of use, wherever the context so require, ‘You’ shall mean any natural 
                                    or legal person who has agreed to become a member of the Website by providing Registration Data while 
                                    registering on the Website as a Registered User. 
                                </p>
                                <p class="each-p">
                                    When you use any of the services provided by Marketlada.com, including but not limited to, (e.g., 
                                    Customer Reviews), you will be subject to the rules, guidelines, policies, terms, and conditions 
                                    applicable to such service, and they shall be deemed to be incorporated into this Terms of Use 
                                    and shall be considered as part and parcel of this Terms of Use. Marketlada.com.com reserves the 
                                    right, at its sole discretion, to change, modify, add or remove portions of these Terms of Use, 
                                    at any time. It is your responsibility to check these Terms of Use periodically for changes. 
                                    Your continued use of the Site following the posting of changes will mean that you accept and 
                                    agree to the changes. As long as you comply with these Terms of Use, Marketlada Limited grants
                                    you a personal, non-exclusive, non-transferable, limited privilege to enter and use the Site. 
                                </p>
                                <p class="each-p">
                                    <strong class="important-text">accessing, browsing or otherwise using the site indicates your agreement to all the terms and 
                                        conditions in this agreement, so please read this agreement carefully before proceeding 
                                    </strong>
                                </p>
                            </div>
                       </section>
                       <section>
                            <h2 class="each-h2-heading">Market Eligibility</h2>
                            <p class="top-text">
                                Use of the Marketlada Website is available only to persons who can form legally binding contracts under 
                                Nigerian governing laws. If you are a minor i.e. under the age of 18 years, you shall not register as 
                                a member of Marketlada.com and shall not transact or use Marketlada.com website. As a minor if you wish 
                                to use or transact on Marketlada.com, such use or transaction may be made by your legal guardian or parents 
                                who have registered as users of Marketlada.com.  Marketlada.com reserves the right to terminate your membership 
                                and refuse to provide you with access to Marketlada.com if it is brought to Marketlada Limited’s notice or if it 
                                is discovered that you are under the age of 18 years. 
                            </p>
                        </section>
                        <section>
                            <h2 class="each-h2-heading">Your account and registration obligations</h2>
                            <p class="top-text">
                                If you use Marketlada.com, you shall be responsible for maintaining the confidentiality of your User ID and Password 
                                and you shall be responsible for all activities that occur under your User ID and Password. You agree that if you 
                                provide any information that is untrue, inaccurate, not current or incomplete that Marketlada.com has reasonable 
                                grounds to suspect that such information is untrue, inaccurate, not current or incomplete, or not in accordance 
                                with this Terms of Use, Marketlada.com has the right to indefinitely suspend or terminate or block access of your 
                                membership with Marketlada.com and refuse to provide you with access to the Website. 
                            </p>
                        </section>
                        <section>
                            <h2 class="each-h2-heading">communications</h2>
                            <p class="top-text">
                                When You use the Website or send emails or other data, information or communication to Marketlada.com, You agree and 
                                understand that You are communicating with Marketlada.com through electronic records and You consent to receive communications 
                                via electronic records from Marketlada.com periodically. Marketlada.com may communicate with You by email or by such other mode 
                                of communication, electronic or otherwise. 
                            </p>
                        </section>
                        <section>
                            <h2 class="each-h2-heading">charges</h2>
                            <p class="top-text">
                                Membership on Marketlada.com is free. Marketlada.com does not charge any fee for browsing and buying on Marketlada.com. However, 
                                Marketlada.com reserves the right to charge a fee and change its policies from time to time. In particular, Marketlada.com may at 
                                its sole discretion introduce new services and modify some or all of the existing services offered on Marketlada.com. In such an 
                                event Marketlada.com reserves, without notice to You, the right to introduce fees for the new services offered or amend/introduce 
                                fees for existing services, as the case may be. Changes to the Fee and related policies shall automatically become effective 
                                immediately once implemented on Marketlada.com. Unless otherwise stated, all fees shall be quoted in Nigerian Naira. You shall be 
                                solely responsible for compliance of all applicable laws including those in Nigeria for making payments to Marketlada.com. 
                            </p>
                        </section>
                       <section>
                           <h2 class="each-h2-heading">Use of Marketlada.com website</h2>
                           <p class="top-text">You agree, undertake and confirm that your use of Marketlada.com shall be strictly governed by the following binding principles: </p>
                           <p class="each-p">You shall not host, display, upload, modify, publish, transmit, update or share any information that: </p>
                           <ol class="use-ol align-list">
                               <li>Belongs to another person and to which You do not have any right. </li>
                               <li>
                                Is grossly harmful, harassing, blasphemous, defamatory, obscene, pornographic, paedophilic, libellous, invasive of another's 
                                privacy, hateful, or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, or otherwise 
                                unlawful in any manner whatever; or unlawfully threatening or unlawfully harassing including but not limited to "indecent representation 
                                of women" or misleading in any way.
                               </li>
                               <li>
                                Is patently offensive to the online community, such as sexually explicit content, or content that promotes 
                                obscenity, pedophilia, racism, bigotry, hatred or physical harm of any kind against any group or individual;  
                               </li>
                               <li>Harasses or advocates harassment of another person; </li>
                               <li>Involves the transmission of "junk mail," "chain letters," or unsolicited mass mailing or "spamming"; </li>
                               <li>Promotes illegal activities or conduct that is abusive, threatening, obscene, defamatory or libelous;</li>
                               <li>
                                 Infringes upon or violates any third party's rights [(including, but not limited to, intellectual property rights, rights of privacy 
                                 (including without limitation unauthorized disclosure of a person's name, email address, physical address or phone number) or rights 
                                 of publicity]; 
                               </li>
                               <li>
                                 Promotes an illegal or unauthorized copy of another person's copyrighted work (see "Copyright complaint" below for instructions on 
                                 how to lodge a complaint about uploaded copyrighted material), such as providing pirated computer programs or links to them, providing 
                                 information to circumvent manufacture-installed copy-protect devices, or providing pirated music or links to pirated music files;
                               </li>
                               <li>Contains restricted or password-only access pages, or hidden pages or images (those not linked to or from another accessible page);</li>
                               <li>Provides material that exploits people in a sexual, violent or otherwise inappropriate manner or solicits personal information from anyone;</li>
                               <li>Provides instructional information about illegal activities such as making or buying illegal weapons, violating someone's privacy, 
                                    or providing or creating computer viruses; 
                                </li>
                                <li>
                                    Contains video, photographs, or images of another person age 18 or older without his or her express written consent 
                                    and permission or those of any minor (regardless of whether you have consent from the minor or his or her legal guardian).
                                </li>
                                <li>
                                    Tries to gain unauthorized access or exceeds the scope of authorized access (as defined herein and in other applicable Codes of 
                                    Conduct or End User Access and License Agreements) to the Sites or to profiles, blogs, communities, account information, bulletins, 
                                    friend request, or other areas of the Sites or solicits passwords or personal identifying information for commercial or unlawful 
                                    purposes from other users; 
                                </li>
                                <li>
                                    Engages in commercial activities and/or sales without Marketlada's prior written consent such as contests, sweepstakes, 
                                    barter, advertising and pyramid schemes, or the buying or selling of "virtual" items related to the Sites. Throughout 
                                    this Terms of Use, Marketlada. "prior written consent" means a communication coming from Marketlada’s Legal department, 
                                    specifically in response to your request, and specifically addressing the activity or conduct for which you seek authorization;
                                </li>
                                <li>
                                    Solicits gambling or engages in any gambling activity which Marketlada, in its sole discretion, believes is or 
                                    could be construed as being illegal;
                                </li>
                                <li>
                                    Interferes with another user's use and enjoyment of Marketlada.com Website or any other individual's user and enjoyment of similar services; 
                                </li>
                                <li>
                                    Refers to any website or URL that, in the sole discretion of Marketlada, contains material that is inappropriate for the Marketlada.com Website or 
                                    any other Website, contains content that would be prohibited or violates the letter or spirit of these Terms of Use. 
                                </li>
                                <li>Harm minors in any way; </li>
                                <li>Infringes any patent, trademark, copyright or other proprietary rights or third party’s trade secrets or rights of publicity or privacy or 
                                    shall not be fraudulent or involve the sale of counterfeit or stolen items; 
                                </li>
                                <li>Violates any law for the time being in force;</li>
                                <li>
                                    Deceives or misleads the addressee/users about the origin of such messages or communicates any information which is grossly 
                                    offensive or menacing in nature;
                                </li>
                                <li>Impersonate another person; </li>
                                <li>
                                    Contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality 
                                    of any computer resource; or contains any Trojan horses, worms, time bombs, cancelbots, easter eggs or other computer programming 
                                    routines that may damage, detrimentally interfere with, diminish value of, surreptitiously intercept or expropriate any system, 
                                    data or personal information;
                                </li>
                                <li>
                                    Threatens the unity, integrity, defence, security or sovereignty of The Federal Republic of Nigeria, friendly relations with foreign 
                                    states, or public order or causes incitement to the commission of any cognizable offence or prevents investigation of any offence or 
                                    is insulting any other nation.
                                </li>
                                <li>Shall not be false, inaccurate or misleading;</li>
                                <li>
                                    Shall not, directly or indirectly, offer, attempt to offer; trade or attempt to trade in any item, the dealing of which is prohibited 
                                    or restricted in any manner under the provisions of any applicable law, rule, regulation or guideline for the time being in force.
                                </li>
                                <li>Shall not create liability for us or cause us to lose (in whole or in part) the services of our ISPs or other suppliers;</li>
                                <li>
                                    You shall not use any “deep-link”, “page-scrape”, “robot”, “spider” or other automatic device, program, algorithm or methodology, or 
                                    any similar or equivalent manual process, to access, acquire, copy or monitor any portion of the Website or any Content, or in any way 
                                    reproduce or circumvent the navigational structure or presentation of the Website or any Content, to obtain or attempt to obtain any 
                                    materials, documents or information through any means not purposely made available through the Website. Marketlada reserves the right 
                                    to bar any such activity. 
                                </li>
                                <li>
                                    You shall not attempt to gain unauthorized access to any portion or feature of Marketlada.com website, or any other systems or networks 
                                    connected to Marketlada.com Website or to any Marketlada server, computer, network, or to any of the services offered on or through 
                                    Marketlada.com Website, by hacking, password “mining” or any other illegitimate means. 
                                </li>
                                <li>
                                    You shall not probe, scan or test the vulnerability of Marketlada website or any network connected to Marketlada.com website nor breach 
                                    the security or authentication measures on Marketlada.com website or any network connected to the Website. 
                                </li>
                                <li>
                                    You may not reverse look-up, trace or seek to trace any information on any other user of or visitor to Marketlada.com Website, or any other 
                                    customer of Marketlada.com, including any Marketlada.com account not owned by you, to its source, or exploit Marketlada.com Website or any 
                                    service or information made available or offered by or through Marketlada.com Website, in any way where the purpose is to reveal any information, 
                                    including but not limited to personal identification or information, other than your own information, as provided for by Marketlada.com Website. 
                                </li>
                                <li>
                                    You agree that you will not take any action that imposes an unreasonable or disproportionately large load on the infrastructure of Marketlada.com Website 
                                    or Marketlada’s systems or networks, or any systems or networks connected to Marketlada.com. 
                                </li>
                                <li>
                                    You agree not to use any device, software or routine to interfere or attempt to interfere with the proper working of the Website or any transaction 
                                    being conducted on the Website, or with any other person’s use of the Website.; 
                                </li>
                                <li>
                                    You may not forget headers or otherwise manipulate identifiers in order to disguise the origin of any message or transmittal you send to 
                                    Marketlada.com on or through the Website or any service offered on or through the Website. You may not pretend that you are, or that you 
                                    represent, someone else, or impersonate any other individual or entity. 
                                </li>
                                <li>
                                    You may not use the Website or any Content for any purpose that is unlawful or prohibited by these Terms of Use, or to solicit the performance 
                                    of any illegal activity or other activity which infringes the rights of Marketlada.com or others. Solely to enable Marketlada.com to use the 
                                    information you supply us with, so that we are not violating any rights you might have in Your Information, you agree to grant us a non-exclusive, 
                                    worldwide, perpetual, irrevocable, royalty-free, sub-licensable (through multiple tiers) right to exercise the copyright, publicity, database 
                                    rights or any other rights you have in Your Information, in any media now known or not currently known, with respect to Your Information. 
                                    Marketlada.com will only use Your Information in accordance with the terms of use and Marketlada’s Privacy Policy. From time to time, 
                                    you shall be responsible for providing information relating to the items or services proposed to be sold by/to you. In this connection, 
                                    you undertake that all such information shall be accurate in all respects. 
                                </li>
                                <li>You shall not exaggerate or over emphasize the attributes of such items or services so as to mislead other Users in any manner.</li>
                                <li>
                                    You shall not lift (i.e. copy and paste) images of products you want to sell on Marketlada.com from other websites, images to be used
                                    must be original images and not stolen images or content posted on another site. And in the event that you violate this term, you 
                                    hereby indemnify Marketlada of any third party claim thereon. 
                                </li>
                                <li>
                                    You shall not engage in advertising to, or solicitation of, other users of Marketlada.com to buy or sell any products or services, 
                                    including, but not limited to, products or services related being displayed on Marketlada.com or related to Marketlada.com. 
                                    You may not transmit any chain letters or unsolicited commercial or junk email to other users via Marketlada.com. It shall 
                                    be a violation of these Terms of Use to use any information obtained from Marketlada.com  in order to harass, abuse, or harm 
                                    another person, or in order to contact, advertise to, solicit, or sell to another person outside of Marketlada.com without 
                                    Marketlada’s prior explicit consent. In order to protect our users from such advertising or solicitation, Marketlada reserves 
                                    the right to restrict the number of messages or emails which a user may send to other users or to Marketlada in any 24-hour 
                                    period which Marketlada deems appropriate in its sole discretion 
                                </li>
                                <li>
                                    You understand that Marketlada has the right at all times to disclose any information (including the identity of the persons 
                                    providing information or materials on the Marketlada.com Website) as necessary to satisfy any law, regulation or valid governmental 
                                    request. This may include, without limitation, disclosure of the information in connection with investigation of alleged illegal 
                                    activity or solicitation of illegal activity or in response to a lawful court order or subpoena. In addition, we can (and you hereby 
                                    expressly authorize us to) disclose any information about you to law enforcement or other government officials, as we, in our sole 
                                    discretion, believe necessary or appropriate in connection with the investigation and/or resolution of possible crimes, especially 
                                    those that may involve personal injury 
                                </li>
                           </ol>
                           <p class="each-p">
                                Marketlada reserves the right, but has no obligation, to monitor the materials posted on Marketlada.com website. Marketlada shall have 
                                the right to remove or edit any Content that in its sole discretion violates, or is alleged to violate, any applicable law or either 
                                the spirit or letter of these Terms of Use. Notwithstanding this right of Marketlada.com, 
                           </p>
                           <p class="each-p">you remain solely responsible for the content of the materials you post on the marketlada.com website and in your private messages.</p>
                           <p class="each-p">
                                Please be advised that such Content posted does not necessarily reflect the views of Marketlada.com. In no event shall Marketlada assume 
                                or have any responsibility or liability for any Content posted or for any claims, damages or losses resulting from use of Content and/or 
                                appearance of Content on Marketlada.com. You hereby represent and warrant that you have all necessary rights in and to all Content you 
                                provide and all information it contains and that such Content shall not infringe any proprietary or other rights of third parties or 
                                contain any libelous, tortious, or otherwise unlawful information 
                           </p>
                           <p class="each-p">
                                It is possible that other users (including unauthorized users or “hackers”) may post or transmit offensive or obscene materials on Marketlada.com
                                and that you may be involuntarily exposed to such offensive and obscene materials. It is possible that other users(including unauthorized users or “hackers”) 
                                may post or transmit offensive or obscene materials on Marketlada.com and that you may be involuntarily exposed to such offensive and obscene materials. It 
                                also is possible for others to obtain personal information about you due to your use of Marketlada.com, and that the recipient may use such information to 
                                harass or injure you. Marketlada does not approve of such unauthorized uses but by using the Marketlada.com Website you acknowledge and agree that Marketlada 
                                will not be responsible for the use of any personal information that you publicly disclose or share with others on Marketlada.com. Carefully select the type 
                                of information that you publicly disclose or share with others on Marketlada.com. 
                           </p>
                           <p class="each-p">
                                Marketlada shall have all the rights to take necessary action and claim damages that may occur due to your involvement/participation in any way on your own 
                                or through a group(s) of People, intentionally or unintentionally in DoS/DDoS (Distributed Denial of Services). 
                           </p>

                           <section>
                                <h3 class="each-sub-heading">Contents Posted on Site</h3>
                                <p class="top-text">
                                    All text, graphics, user interfaces ,visual interfaces, photographs, trademarks, logos, sounds, music, artwork and computer code (collectively, “Content”), 
                                    including but not limited to the design, structure, selection, coordination, expression, “look and feel” and arrangement of such Content, contained on 
                                    Marketlada.com is owned, controlled or licensed by or to Marketlada Limited, and is protected by trade dress, copyright, patent and trademark laws, and 
                                    various other intellectual property rights and unfair competition laws. 
                                </p>
                                <p class="each-p">
                                    Except as expressly provided in these Terms of Use, no part of Marketlada.com and no Content may be copied, reproduced, re-published, uploaded, posted, 
                                    publicly displayed, encoded, translated, transmitted or distributed in any way (including “mirroring”) to any other computer, server, website or other medium 
                                    for publication or distribution or for any commercial enterprise, without Marketlada’s express prior written consent. You may use information on Marketlada.com 
                                    products and services purposely made available by Marketlada.com for downloading from the site, provided that you
                                </p>
                                <ol class="align-list">
                                    <li>Do not remove any proprietary notice language in all copies of such documents, </li>
                                    <li>
                                    Use such information only for your personal, non-commercial informational purpose and do 
                                    not copy or post such information on any networked computer or broadcast it in any media, 
                                    </li>
                                    <li>Make no modifications to any such information, and </li>
                                    <li>Not make any additional representations or warranties relating to such documents.</li>
                                </ol>
                                <p class="each-p">
                                    You shall be responsible for any notes, messages, e-mails, billboard postings, photos, drawings, profiles, opinions, ideas, images, videos, audio 
                                    files or other materials or information posted or transmitted to the Sites (collectively, “Content"). Such Content will become the property of Marketlada 
                                    and you grant Marketlada Limited the worldwide, perpetual and transferable rights in such Content. Marketlada shall be entitled to, consistent with our 
                                    Privacy Policy, use the Content or any of its elements for any type of use forever, including but not limited to promotional and advertising purposes 
                                    and in any media whether now known or hereafter devised, including the creation of derivative works that may include Content you provide. You agree 
                                    that any Content you post may be used by Marketlada, consistent with our Privacy Policy on Site as mentioned herein, and you are not entitled to any 
                                    payment or other compensation for such use. 
                                </p>
                            </section>
                            <section>
                                <h3 class="each-sub-heading">Other Businesses</h3>
                                <p class="top-text">Marketlada does not take responsibility or liability for the actions, products, content and services on Marketlada.com website, which are linked to 
                                    Affiliates and / or third party websites using Marketlada.com APIs or otherwise. In addition, Marketlada.com may provide links to the third party 
                                    websites of affiliated companies and certain other businesses for which, Marketlada assumes no responsibility for examining or evaluating the products 
                                    and services offered by them, and Marketlada does not warrant the offerings of, any of these businesses or individuals or the content of such third party 
                                    website(s). Marketlada.com does not in any way endorse any third party website(s) or content thereof. 
                                </p>
                            </section>
                            <section>
                                <h3 class="each-sub-heading">Links</h3>
                                <p class="top-text">Marketlada.com welcomes links to this site. You may establish a hypertext link to Marketlada.com website, provided that the link does not state or imply 
                                    any sponsorship or endorsement of your site by Marketlada.com. You must not use on your site or in any other manner any trademarks, service marks or any 
                                    other materials appearing on Marketlada.com, including any logos or characters, without the express written consent of Marketlada.com and the owner of the 
                                    mark or materials. You must not frame or otherwise incorporate into another third party website or present in conjunction with or juxtaposed against such 
                                    a website any of the content or other materials on the Marketlada.com website without Marketlada’s prior written consent. 
                                </p>
                            </section>
                            <section>
                                <h3 class="each-sub-heading">Privacy</h3>
                                <p class="top-text">We view protection of Your privacy as a very important principle. We understand clearly that you and Your Personal Information is one of our most important assets.
                                    We store and process Your Information on computers that may be protected by physical as well as reasonable technological security measures and procedures in 
                                    accordance with National Information Technology Development Agency Act 2007 and rules there under. Our current Privacy Policy is available at our website. If 
                                    you object to your Information being transferred or used in this way, please do reach out to our team for possible resolution of the problem.
                                </p>
                            </section>
                       </section>
                       <section>
                           <h2 class="each-h2-heading">Mandatory Declaration</h2>
                           <ol class="align-list">
                               <li>You hereby declare that you have provided all necessary Legal Delivery Details for the shipment of the product to the destination specified by you in the Order. </li>
                               <li>You further declare that the Product will be acquired for personal use of the Consignee and/or Buyer. The Product will not be sold, resold, bartered or 
                                   in any way disposed for profit. 
                                </li>
                                <li>Where the goods will be resold, kindly send an email to us for this purpose. </li>
                           </ol>
                           <section>
                               <h3 class="each-sub-heading">Disclaimer of warranties and liability</h3>
                               <p class="top-text">This website, all the materials and products (including but not limited to software) and services, included on or otherwise made available to you through 
                                   this site are provided on Marketlada.com on “as is” and “as available” basis without any representation or warranties, express or implied except otherwise 
                                   specified in writing. Without prejudice to the forgoing paragraph, Marketlada.com does not warrant that: 
                                </p>
                                <ul class="align-list">
                                    <li>This website will be constantly available, or available at all times; or </li>
                                    <li>The information on this website is complete, true, accurate or non-misleading. </li>
                                </ul>
                                <p class="each-p">Marketlada will not be liable to you in any way or in relation to the contents of, or use of, or otherwise in connection with, Marketlada.com website. </p>
                                <p class="each-p">Marketlada does not warrant that this site; information, content, materials, product (including software) or services included on or otherwise made 
                                    available to you through Marketlada.com website; their servers; or electronic communication sent from Marketlada.com are free of viruses or other 
                                    harmful components. 
                                </p>
                                <p class="each-p">Nothing on Marketlada.com constitutes, or is meant to constitute, advice of any kind. </p>
                                <p class="each-p">All the products sold on Marketlada.com are governed by laws of The Federal Republic of Nigeria and if Marketlada is unable to deliver such products 
                                    due to implications of the laws, Marketlada will return or will give credit for the amount received by Marketlada from the sale of such product, 
                                    which could not be delivered to you. You will be required to enter a valid phone number while placing an order on Marketlada.com. By registering 
                                    your phone number with us, you consent to be contacted by Marketlada via phone calls and / or SMS notifications, in case of any order or shipment or 
                                    delivery related updates. Marketlada will not use your personal information to initiate any promotional phone calls or SMS'. 
                                </p>
                           </section>
                           <section>
                               <h3 class="each-sub-heading">Services</h3>
                               <ul>
                                   <div class="align-list">
                                        <li>Payment</li>
                                        <p class="each-p">While availing any of the payment method(s) offered at Marketlada.com, Marketlada.com will not be responsible or assume any liability, whatsoever 
                                            in respect of any loss or damage arising directly or indirectly to you due to: 
                                        </p>
                                        <ol class="align-list">
                                            <li>Lack of authorization for any transaction(s), or </li>
                                            <li>Exceeding the preset limit mutually agreed by you and between your "Bank(s)", or </li>
                                            <li>Any payment issues arising out of the transaction, or </li>
                                            <li>Decline of transaction for any other reason/s.</li>
                                        </ol>
                                        <p class="each-p">All payments made against the purchases/services on Marketlada.com by you shall be compulsorily in Nigerian Naira acceptable by the Central Bank of 
                                            Nigeria. Marketlada.com does not accept any other form of currency with respect to the purchases made on Marketlada. 
                                        </p>
                                   </div>
                                   <div class="align-list">
                                        <li>Breach</li>
                                        <p class="each-p">Without limiting other remedies, Marketlada.com may limit your activity, immediately remove your information, warn other Users of your actions, 
                                            immediately temporarily/indefinitely suspend or terminate or block your membership, and/or refuse to provide you with access to Marketlada.com 
                                            website in the event, but not limited to: 
                                        </p>
                                        <ol class="align-list">
                                            <li>If you breach the Terms of Use or Privacy Policy or other rules and policies, if any; </li>
                                            <li>If Marketlada.com is unable to verify or authenticate any information you provide; or</li>
                                            <li>If it is believed that your actions may cause legal liability for you, other Users or Marketlada.com.</li>
                                        </ol>
                                        <p class="each-p">Marketlada.com may at any time at its sole discretion reinstate suspended users. A User that has been suspended or blocked may not register or attempt 
                                            to register with Marketlada.com or use Marketlada.com Website in any manner whatsoever until such time that such User is reinstated by Marketlada.com. 
                                            Notwithstanding the foregoing, if you breach the Terms of Use or Privacy Policy or other rules and policies, Marketlada.com reserves the right to recover 
                                            any amounts due and owing by you to Marketlada.com and to take strict legal action including but not limited to a referral to the appropriate law enforcement 
                                            or other authorities for initiating criminal or other proceedings against you. 
                                        </p>
                                   </div>
                                   <div class="align-list">
                                        <li>Indemnity</li>
                                        <p class="each-p">You shall indemnify and hold harmless Marketlada.com its owner, licensee, affiliates, subsidiaries, group companies (as applicable) and their respective officers, 
                                            directors, agents, and employees, from any claim or demand, or actions including attorneys' fees, made by you or any third party or penalty imposed due to or arising 
                                            out of your use of the goods or services, or in the event you breach this Terms of Use, the Privacy Policy and other Policies, or your violation of any law, rules or 
                                            regulations or the rights of a third party on Marketlada.com
                                        </p>
                                   </div>
                                   <div class="align-list">
                                       <li>Applicable Law</li>
                                        <p class="each-p">This Agreement shall be governed by and interpreted and construed in accordance with the laws of The Federal Republic of Nigeria. The place of jurisdiction shall 
                                            be exclusively in Nigeria. 
                                        </p>
                                   </div>
                                   <div class="align-list">
                                       <li>Jurisdictional Issues/Sale in Nigeria Only</li>
                                        <p class="each-p">Unless otherwise specified, the material on Marketlada.com is presented solely for the purpose of sale in Nigeria. Marketlada makes no representation that 
                                            materials/services in Marketlada.com are appropriate or available for use in other locations/Countries other than Nigeria. Those who choose to access this 
                                            site from other locations/Countries other than Nigeria do so on their own initiative and Marketlada is not responsible for supply of goods/availability of 
                                            services, refund for the goods or services ordered from other locations/Countries other than Nigeria, compliance with local laws, if and to the extent 
                                            local laws are applicable. 
                                        </p>
                                   </div>
                                   <div class="align-list">
                                       <li>Trademark, Copyright and Restriction</li>
                                        <p class="each-p">This site is controlled and operated by Marketlada Limited. All material on this site, including images, illustrations, audio clips, and video clips, are 
                                            protected by copyrights, trademarks, and other intellectual property rights that are owned and controlled by us or by other parties that have licensed their 
                                            material to us. Material on Marketlada.com  web site owned, operated, licensed or controlled by us is solely for your personal, non-commercial use. You must not 
                                            copy, reproduce, republish, upload, post, transmit or distribute such material in any way, including by e-mail or other electronic means and whether directly or 
                                            indirectly and you must not assist any other person to do so. Without the prior written consent of the owner, modification of the materials, use of the materials 
                                            on any other web site or networked computer environment or use of the materials for any purpose other than personal, noncommercial use is a violation of the copyrights, 
                                            trademarks and other proprietary rights, and is prohibited. Any use for which you receive any remuneration, whether in money or otherwise, is a commercial use for the 
                                            purposes of this clause. 
                                        </p>
                                   </div>
                                   <div class="align-list">
                                       <li>Copyright complaint</li>
                                        <p class="each-p">We at Marketlada.com respect the intellectual property of others. In case you feel that your work has been copied in a way that constitutes copyright infringement 
                                            you can write to us <a href="">help@marketlada.com</a>
                                        </p>
                                   </div>
                                   <div class="align-list">
                                       <li>Risk of loss</li>
                                        <p class="each-p">All items purchased from Marketlada.com are made pursuant to a shipment contract. This means that the Risk of Loss shall remain with Marketlada.com until the item is 
                                            transferred to You. In the event that the items are damaged after receipt, the risk falls on the customer. 
                                        </p>
                                   </div>
                                   <div class="align-list">
                                       <li>Product and Service Description</li>
                                        <p class="each-p">Marketlada.com tries to be as accurate as possible. However, Marketlada.com does not warrant that product or service description or other content of this site is accurate, 
                                            complete, reliable, current, or error-free. If a product or service offered on Marketlada.com itself is not as described, your sole remedy is to return it in unused condition. 
                                        </p>
                                   </div>
                                   <div class="align-list">
                                       <li>Pricing and Typographical error</li>
                                        <p class="each-p">If Marketlada.com comes across any difference in pricing resulting from typographic errors with regards to pricing or product/service information, Marketlada.com shall have the 
                                            right to rectify the same or cancel the order(s) and refund monies, if any, collected from the customer within 10-15 business days of such corrective action taken. The mode of 
                                            refund will be the same as at the time of placing the order. Cash on Delivery order refunds will be 
                                        </p>
                                   </div>
                                   <div class="align-list">
                                       <li>Cancellation of order</li>
                                        <p class="top-text">Marketlada.com reserves the right to cancel any order without any explanation for doing so, under situation where Marketlada.com is not able to meet the requirement of the order 
                                            placed or order so placed/cancelled does not comply with the Marketlada.com policy or for any reason. However, Marketlada.com will ensure that any communication of cancellation 
                                            of an order is intimated within appropriate time to the concerned person and any applicable refund, will be made in reasonable time. 
                                        </p>
                                        <p class="each-p">Note that in the event of cancellation of a ‘pay on delivery’ orders, Marketlada will not be liable in any form where the customer proceeds to receive orders following 
                                            an earlier cancellation. 
                                        </p>
                                   </div>
                                   <div class="align-list">
                                       <li>Termination of service</li>
                                        <p class="each-p">Marketlada.com reserves the absolute right to modify, discontinue, temporarily or permanently, any and all portion of our goods and services with or without prior communications. 
                                            You hereby consent that Marketlada.com will under no circumstance be liable to you or any third party for any modification or discontinuance of availability of goods or services 
                                            on the website. 
                                        </p>
                                   </div>
                                   <div class="align-list">
                                       <li>Limitation of liability</li>
                                        <p class="each-p important-text">in no event shall <strong>marketlada.com</strong> be liable for any special, incidental, indirect or consequential damages of any kind in connection with this agreement, even if 
                                            <strong>marketlada.com</strong> has been informed in advance of the possibility of such damages. 
                                        </p>
                                        <p class="each-p important-text"><strong>marketlada’s</strong> aggregate liability to you, any individual or any third party in any matter arising herefrom, 
                                            related or connected to our goods and services is at the company’s sole discretion. 
                                        </p>
                                   </div>
                               </ul>
                            </section>
                       </section>
                    </div>
                </section>
            </main>
        </div>
                
    </div>
    <a href="#top-of-site" class="top-of-site-link">
        <svg width="32" height="32" viewBox="0 0 100 100">
            <path fill="white" d="m50 0c-13.262 0-25.98 5.2695-35.355 14.645s-14.645 22.094-14.645 35.355 5.2695 25.98 14.645 35.355 22.094 14.645 35.355 14.645 25.98-5.2695 35.355-14.645 14.645-22.094 14.645-35.355-5.2695-25.98-14.645-35.355-22.094-14.645-35.355-14.645zm20.832 62.5-20.832-22.457-20.625 22.457c-1.207 0.74219-2.7656 0.57812-3.7891-0.39844-1.0273-0.98047-1.2695-2.5273-0.58594-3.7695l22.918-25c0.60156-0.61328 1.4297-0.96094 2.2891-0.96094 0.86328 0 1.6914 0.34766 2.293 0.96094l22.918 25c0.88672 1.2891 0.6875 3.0352-0.47266 4.0898-1.1562 1.0508-2.9141 1.0859-4.1133 0.078125z"></path>
        </svg>
    </a>
    @include('partials.frontend._footerii')  
    
    <script src="/js/script.js"></script>
    <script src="/js/user.js"></script>
    
</body>
</html>